{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app.name }}-public
spec:
  entryPoints:
    - {{ default "websecure" .Values.ingress.publicEntryPoints }}
  {{- if .Values.app.path }}
  middleware:
    name: {{ .Values.app.name }}
    namespace: {{ .Values.app.name }}
  {{- end }}
  routes:
    - match:  Host(`{{ .Values.app.dns }}`) && PathPrefix(`/{{ .Values.app.path }}`)
      kind: Rule
      services:
        - name: {{ .Values.app.name }}
          namespace: {{ .Values.app.name }}
          port: {{ default "80" .Values.service.port }}
          scheme: {{ default "http" .Values.service.scheme }}
  tls:
    secretName: {{ .Values.app.name }}
{{- end }}
